# Generated by Django 3.2.7 on 2021-10-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoweb', '0002_auto_20210919_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='shutter_tags',
            field=models.TextField(blank=True, null=True, verbose_name='shutter tags'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
