# Generated by Django 3.2.7 on 2021-11-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoweb', '0005_auto_20211121_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200, unique=True, verbose_name='path')),
                ('no_show', models.BooleanField(default=False, verbose_name='no show')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_dt')),
                ('updated_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_dt')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('position', models.IntegerField(blank=True, default=0, verbose_name='position')),
            ],
        ),
    ]
