# Generated by Django 3.2.7 on 2021-11-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoweb', '0006_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='cover'),
        ),
    ]
