# Generated by Django 3.2.7 on 2021-12-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoweb', '0009_album_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
