# Generated by Django 3.2.10 on 2022-01-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoweb', '0010_alter_album_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='aws_tags',
            field=models.TextField(blank=True, null=True, verbose_name='aws tags'),
        ),
    ]
