# Generated by Django 3.2.10 on 2022-01-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoweb', '0011_image_aws_tags'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE fotoweb_image ADD FULLTEXT" +
            "(name,path,mykeyworder_tags,adobe_tags,google_tags,aws_tags,shutter_tags,title,description,tags)")
    ]

