# Generated by Django 3.2.10 on 2022-01-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoweb', '0012_alter_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='level',
            field=models.IntegerField(default=0, verbose_name='level'),
        ),
    ]
