# Generated by Django 3.2.10 on 2022-01-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoweb', '0013_album_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pexels',
            field=models.BooleanField(default=False, verbose_name='pexels'),
        ),
        migrations.AddField(
            model_name='image',
            name='pexels_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pexels_dt'),
        ),
        migrations.AddField(
            model_name='image',
            name='pexels_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='pexels_url'),
        ),
        migrations.AddField(
            model_name='image',
            name='rasfocus',
            field=models.BooleanField(default=False, verbose_name='rasfocus'),
        ),
        migrations.AddField(
            model_name='image',
            name='rasfocus_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rasfocus_dt'),
        ),
        migrations.AddField(
            model_name='image',
            name='rasfocus_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='rasfocus_url'),
        ),
    ]
