# Generated by Django 3.2.10 on 2022-01-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoweb', '0014_auto_20220121_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='private',
            field=models.BooleanField(default=False, verbose_name='private'),
        ),
    ]
