# Generated by Django 4.2.3 on 2023-08-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoweb', '0017_alter_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='path_fs',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='path'),
        ),
        migrations.AddField(
            model_name='image',
            name='url_fs',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='url'),
        ),
    ]
