# Generated by Django 4.1.7 on 2023-05-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoweb', '0017_alter_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='instagram',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Posted'), (2, 'Queued')], default=0, verbose_name='instagram'),
        ),
    ]
