# Generated by Django 4.2.9 on 2024-03-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotoweb', '0018_alter_image_instagram'),
        ('fotoweb', '0018_image_path_fs_image_url_fs'),
    ]

    operations = [
    ]
