# Generated by Django 4.2.9 on 2024-03-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoweb', '0019_merge_20240317_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='image',
            name='path_fs',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='path fs'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url_fs',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='url fs'),
        ),
    ]
