# Generated by Django 4.2.9 on 2024-05-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoweb', '0020_album_comments_alter_image_path_fs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='domain',
            field=models.IntegerField(choices=[(1, 'Vallka'), (2, 'Lucas'), (3, 'Gellifique')], default=1),
        ),
    ]
