# Generated by Django 4.2.9 on 2024-05-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoweb', '0021_album_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='taken_dt',
            field=models.DateField(null=True, verbose_name='taken_dt'),
        ),
    ]
