# Generated by Django 4.2.9 on 2024-05-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoweb', '0022_album_taken_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='domain',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='album',
            name='taken_dt',
            field=models.DateField(blank=True, null=True, verbose_name='taken_dt'),
        ),
    ]
