# Generated by Django 3.2 on 2021-06-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gellifinsta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='Tag')),
                ('shortcode', models.CharField(max_length=20, unique=True, verbose_name='Shortcode')),
                ('taken_at_timestamp', models.IntegerField(verbose_name='taken at ts')),
                ('taken_at_datetime', models.DateTimeField(verbose_name='taken at')),
                ('display_url', models.CharField(max_length=500, verbose_name='display_url')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('username', models.CharField(max_length=100, verbose_name='Shortcode')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('local_fname', models.CharField(max_length=500, verbose_name='local_fname')),
                ('remote_fname', models.CharField(max_length=500, verbose_name='local_fname')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date/Time')),
                ('updated_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date/Time')),
            ],
            options={
                'ordering': ['-taken_at_timestamp'],
            },
        ),
    ]
