# Generated by Django 3.2 on 2021-06-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gellifinsta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gellifinsta',
            name='shortcode',
            field=models.CharField(max_length=20, verbose_name='Shortcode'),
        ),
    ]
