# Generated by Django 3.2.4 on 2021-06-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gellifinsta', '0002_alter_gellifinsta_shortcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='gellifinsta',
            options={'ordering': ['-taken_at_datetime']},
        ),
        migrations.RemoveField(
            model_name='gellifinsta',
            name='display_url',
        ),
        migrations.RemoveField(
            model_name='gellifinsta',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='gellifinsta',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='gellifinsta',
            name='taken_at_timestamp',
        ),
        migrations.RemoveField(
            model_name='gellifinsta',
            name='user_id',
        ),
        migrations.AddField(
            model_name='gellifinsta',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='gellifinsta',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Username'),
        ),
    ]
