# Generated by Django 3.2.4 on 2021-06-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gellifinsta', '0003_auto_20210622_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gellifinsta',
            old_name='local_fname',
            new_name='file_path',
        ),
    ]
