# Generated by Django 3.2.4 on 2021-06-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gellifinsta', '0004_rename_local_fname_gellifinsta_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gellifinsta',
            old_name='remote_fname',
            new_name='url',
        ),
    ]
