# Generated by Django 3.2.4 on 2021-06-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gellifinsta', '0006_auto_20210623_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='gellifinsta',
            name='is_video',
            field=models.BooleanField(default=False, verbose_name='Video'),
        ),
    ]
