# Generated by Django 3.1.2 on 2021-09-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gellifinsta', '0007_gellifinsta_is_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gellifinsta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
