# Generated by Django 3.1.2 on 2020-11-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsshot',
            name='note',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
