# Generated by Django 3.2.13 on 2022-05-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castle',
            name='grid_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
