# Generated by Django 3.2.13 on 2022-05-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castles', '0002_alter_castle_grid_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='castle',
            name='canmore_map',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='castle',
            name='canmore_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
