# Generated by Django 3.1 on 2020-08-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Category'),
        ),
    ]
