# Generated by Django 3.1 on 2020-08-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.BooleanField(default=False, verbose_name='Publish to blog'),
        ),
        migrations.AddField(
            model_name='post',
            name='blog_start_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publish Date/Time'),
        ),
        migrations.AddField(
            model_name='post',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date/Time'),
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.BooleanField(default=False, verbose_name='Send as newsletter'),
        ),
        migrations.AddField(
            model_name='post',
            name='email_end_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Send Date/Time'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date/Time'),
        ),
    ]
