# Generated by Django 3.1.2 on 2020-11-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200828_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='email_end_dt',
            new_name='email_send_dt',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Title'),
        ),
    ]
