# Generated by Django 3.1.2 on 2020-11-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201106_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email_status',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Sending'), (2, 'Sent')], default=0),
        ),
    ]
