# Generated by Django 3.1.6 on 2021-02-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210225_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_bgcolor',
            field=models.CharField(blank=True, default='#eeeeee', max_length=20, verbose_name='Title Bg Color'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_color',
            field=models.CharField(blank=True, default='#232323', max_length=20, verbose_name='Title Color'),
        ),
    ]
