# Generated by Django 3.1.2 on 2021-09-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210225_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.BooleanField(default=False, verbose_name='Send as newsletter to UK customers'),
        ),
    ]
