# Generated by Django 3.2.7 on 2021-12-18 21:32

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20211011_1927'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE blog_post ADD FULLTEXT(title, text)")
    ]
