# Generated by Django 3.2.7 on 2021-12-27 16:23

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='Text'),
        ),
    ]
